apiVersion: v1
kind: ConfigMap
metadata:
  name: ohmf-gateway-config
  namespace: ohmf-app
data:
  APP_OTP_START_PER_IP_LIMIT: "20000"
  APP_OTP_START_PER_SUBNET_LIMIT: "50000"
  APP_OTP_VERIFY_PER_IP_LIMIT: "50000"
  APP_WS_CONNECT_PER_IP_LIMIT: "20000"
  APP_WS_CONNECT_BURST: "20000"
  APP_SEND_RATE_PER_IP: "20000"
  APP_SEND_RATE_IP_BURST: "20000"
  APP_SEND_RATE_PER_CONVERSATION: "4000"
  APP_SEND_RATE_CONVERSATION_BURST: "8000"
