apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: gateway-config-patch.yaml
  - path: gateway-deployment-patch.yaml
  - path: gateway-hpa-patch.yaml
  - path: messages-processor-deployment-patch.yaml
  - path: messages-processor-hpa-patch.yaml
  - path: delivery-processor-deployment-patch.yaml
  - path: delivery-processor-hpa-patch.yaml
  - path: sms-processor-deployment-patch.yaml
