apiVersion: v1
kind: Service
metadata:
  name: ohmf-gateway
  namespace: ohmf-app
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: edge
  ports:
    - name: http
      port: 8080
      targetPort: http
