apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ohmf-messages-processor
  namespace: ohmf-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: messages-processor
