apiVersion: v1
kind: Namespace
metadata:
  name: ohmf-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: ohmf-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: ohmf-loadgen
---
apiVersion: v1
kind: Namespace
metadata:
  name: ohmf-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: ohmf-chaos
