apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ohmf-sms-processor
  namespace: ohmf-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sms-processor
