apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohmf-sms-processor
  namespace: ohmf-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sms-processor
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sms-processor
        app.kubernetes.io/component: worker
    spec:
      priorityClassName: ohmf-workers-medium
      nodeSelector:
        ohmf.node-role: app
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: sms-processor
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: sms-processor
      containers:
        - name: sms-processor
          image: ohmf-sms-processor:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ohmf-processors-config
            - secretRef:
                name: ohmf-app-secrets
          env:
            - name: APP_KAFKA_GROUP_ID
              value: sms-processor-v1
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
