apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ohmf-gateway
  namespace: ohmf-observability
spec:
  namespaceSelector:
    matchNames:
      - ohmf-app
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: edge
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
