apiVersion: v1
kind: Secret
metadata:
  name: ohmf-app-secrets
  namespace: ohmf-app
type: Opaque
stringData:
  APP_DB_DSN: postgres://ohmf:change-me@postgres-rw.ohmf-data.svc.cluster.local:5432/ohmf?sslmode=require
  APP_REDIS_ADDR: redis-primary.ohmf-data.svc.cluster.local:6379
  APP_REDIS_DB: "0"
  APP_JWT_SECRET: replace-me
  APP_KAFKA_BROKERS: kafka-bootstrap.ohmf-data.svc.cluster.local:9092
  APP_CASSANDRA_HOSTS: cassandra.ohmf-data.svc.cluster.local:9042
  APP_CASSANDRA_KEYSPACE: ohmf_messages
  APP_CASSANDRA_CONSISTENCY: quorum
