#!/usr/bin/env python3
"""
Count non-comment, non-blank lines of code across a repository.

Usage: python scripts/count_loc.py [root]

Heuristics:
- Skips files with common binary extensions and common generated-file markers.
- Skips directories like .git, node_modules, postgres-data, vendor, dist, build.
- Detects single-line comments and C-style /* */ blocks for many languages.
"""
import os
import sys
import re
from collections import defaultdict

ROOT = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()

EXCLUDE_DIRS = {
    ".git",
    "node_modules",
    "postgres-data",
    "vendor",
    "dist",
    "build",
    "target",
    ".venv",
    "venv",
    ".idea",
    ".vscode",
}

BINARY_EXTS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".class",
    ".jar",
    ".zip",
    ".tar",
    ".gz",
    ".pdf",
    ".pptx",
    ".xlsx",
    ".mp4",
    ".mp3",
    ".woff",
    ".woff2",
}

# Map extensions (or special filenames) to comment markers
SINGLE_LINE_MAP = {
    # C-like
    ".go": "//",
    ".js": "//",
    ".ts": "//",
    ".java": "//",
    ".c": "//",
    ".cpp": "//",
    ".h": "//",
    ".cs": "//",
    ".swift": "//",
    ".kt": "//",
    # Shell / python
    ".py": "#",
    ".sh": "#",
    ".ps1": "#",
    ".rb": "#",
    ".pl": "#",
    ".yml": "#",
    ".yaml": "#",
    ".ini": ";",
    ".toml": "#",
    ".sql": "--",
    ".md": "#",
    ".dockerfile": "#",
}

SPECIAL_FILENAMES = {
    "Dockerfile": "#",
    "Makefile": "#",
}

GENERATED_MARKERS = [
    "do not edit",
    "generated",
    "auto-generated",
    "autogenerated",
    "code generated",
    "generated by",
]

def is_binary_by_ext(path):
    _, ext = os.path.splitext(path.lower())
    return ext in BINARY_EXTS

def contains_generated_marker(text):
    t = text.lower()
    return any(m in t for m in GENERATED_MARKERS)

def detect_comment_marker(path):
    name = os.path.basename(path)
    if name in SPECIAL_FILENAMES:
        return SPECIAL_FILENAMES[name]
    _, ext = os.path.splitext(name)
    return SINGLE_LINE_MAP.get(ext)

def count_file(path):
    # returns tuple: (total_lines, skipped_lines (blank+comment), counted_lines)
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()
    except Exception:
        return (0, 0, 0)

    # Skip if generated by marker in file content or filename
    if contains_generated_marker(text) or contains_generated_marker(os.path.basename(path)):
        return (0, 0, 0)

    lines = text.splitlines()
    total = len(lines)
    skipped = 0
    in_block = False
    # choose marker
    marker = detect_comment_marker(path)

    for line in lines:
        s = line.strip()
        if not s:
            skipped += 1
            continue

        # handle C-style block comments
        if in_block:
            if "*/" in s:
                in_block = False
                # treat this line as comment
                skipped += 1
            else:
                skipped += 1
            continue

        if "/*" in s:
            # start of block comment
            in_block = True
            skipped += 1
            continue

        if marker and s.startswith(marker):
            skipped += 1
            continue

        # fallback: if line starts with common comment symbols
        if s.startswith("//") or s.startswith("#") or s.startswith("--") or s.startswith(";"):
            skipped += 1
            continue

    counted = total - skipped
    return (total, skipped, counted)

def is_excluded_dir(path):
    parts = path.split(os.sep)
    return any(p in EXCLUDE_DIRS for p in parts)

def main():
    totals = defaultdict(int)
    per_lang = defaultdict(lambda: {"files":0, "lines":0, "skipped":0, "code":0})
    files_scanned = 0

    for root, dirs, files in os.walk(ROOT):
        # prune excluded dirs
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith('.')]
        if is_excluded_dir(root):
            continue

        for fname in files:
            path = os.path.join(root, fname)
            # skip markdown specifically
            if fname.lower().endswith('.md'):
                continue
            # skip binary by extension
            if is_binary_by_ext(path):
                continue

            # try to treat as text file
            total, skipped, counted = count_file(path)
            if total == 0 and counted == 0 and skipped == 0:
                # likely binary or unreadable or autogenerated
                continue

            files_scanned += 1
            totals['files'] += 1
            totals['total_lines'] += total
            totals['skipped'] += skipped
            totals['code'] += counted

            _, ext = os.path.splitext(fname)
            key = ext.lower() or fname.lower()
            per_lang[key]['files'] += 1
            per_lang[key]['lines'] += total
            per_lang[key]['skipped'] += skipped
            per_lang[key]['code'] += counted

    print("LOC Summary (heuristic):")
    print(f"Root: {ROOT}")
    print()
    print(f"Files scanned: {totals['files']}")
    print(f"Total lines: {totals.get('total_lines',0):,}")
    print(f"Blank/comment lines skipped: {totals.get('skipped',0):,}")
    print(f"Estimated non-comment lines of code: {totals.get('code',0):,}")
    print()
    print("Breakdown by file extension (top 20):")
    items = sorted(per_lang.items(), key=lambda kv: kv[1]['code'], reverse=True)
    for ext, stats in items[:20]:
        print(f"{ext:8} files={stats['files']:4} code={stats['code']:8,} total={stats['lines']:8,}")

if __name__ == '__main__':
    main()
