// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID              pgtype.UUID
	Type            string
	TransportPolicy string
	Title           pgtype.Text
	LastMessageID   pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ConversationCounter struct {
	ConversationID  pgtype.UUID
	NextServerOrder int64
	UpdatedAt       pgtype.Timestamptz
}

type ConversationMember struct {
	ConversationID      pgtype.UUID
	UserID              pgtype.UUID
	Role                string
	JoinedAt            pgtype.Timestamptz
	LastReadServerOrder int64
}

type Device struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Platform     string
	DeviceName   pgtype.Text
	PushToken    pgtype.Text
	PublicKey    pgtype.Text
	SmsRoleState pgtype.Text
	LastSeenAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID              pgtype.UUID
	ActorUserID     pgtype.UUID
	Endpoint        string
	Key             string
	ResponsePayload []byte
	StatusCode      pgtype.Int4
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type Message struct {
	ID                pgtype.UUID
	ConversationID    pgtype.UUID
	SenderUserID      pgtype.UUID
	SenderDeviceID    pgtype.UUID
	ContentType       string
	Content           []byte
	ClientGeneratedID pgtype.Text
	Transport         string
	ServerOrder       int64
	CreatedAt         pgtype.Timestamptz
}

type PhoneVerificationChallenge struct {
	ID                pgtype.UUID
	PhoneE164         string
	OtpCodeHash       string
	Channel           string
	AttemptsRemaining int32
	ExpiresAt         pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	DeviceID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID               pgtype.UUID
	PrimaryPhoneE164 string
	PhoneVerifiedAt  pgtype.Timestamptz
	DisplayName      pgtype.Text
	AvatarUrl        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
